joint_limits:
  LShoulderYaw:
    has_velocity_limits: true
    max_velocity: 10.333784
    has_acceleration_limits: true
    max_acceleration: 2.0667568
  LWristPitch:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: true
    max_acceleration: 0
  LShoulderPitch:
    has_velocity_limits: true
    max_velocity: 6.52664058
    has_acceleration_limits: true
    max_acceleration: 1.305328116
  LElbowRoll:
    has_velocity_limits: true
    max_velocity: 10.333784
    has_acceleration_limits: true
    max_acceleration: 2.0667568
  RWristPitch:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: true
    max_acceleration: 0
  RWristYaw:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: true
    max_acceleration: 0
  LWristRoll:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: true
    max_acceleration: 0
  LWristYaw:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: true
    max_acceleration: 0
  RShoulderYaw:
    has_velocity_limits: true
    max_velocity: 10.333784
    has_acceleration_limits: true
    max_acceleration: 2.0667568
  RElbowRoll:
    has_velocity_limits: true
    max_velocity: 10.333784
    has_acceleration_limits: true
    max_acceleration: 2.0667568
  RElbowYaw:
    has_velocity_limits: true
    max_velocity: 10.3810644
    has_acceleration_limits: true
    max_acceleration: 2.07621288
  RWristRoll:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: true
    max_acceleration: 0
  LElbowYaw:
    has_velocity_limits: true
    max_velocity: 10.3810644
    has_acceleration_limits: true
    max_acceleration: 2.07621288
  RShoulderPitch:
    has_velocity_limits: true
    max_velocity: 6.52664058
    has_acceleration_limits: true
    max_acceleration: 1.305328116